#!/bin/bash
# show charm palette swatches for validating how colors look
swatch() {
  local hex="$1" name="$2" role="$3"
  local r=$((16#${hex:1:2})) g=$((16#${hex:3:2})) b=$((16#${hex:5:2}))
  printf "\033[48;2;%d;%d;%dm    \033[0m " "$r" "$g" "$b"
  printf "\033[38;2;%d;%d;%dm%-10s\033[0m  %-12s %s\n" "$r" "$g" "$b" "$hex" "$name" "$role"
}

echo ""
echo "  Charmtone Pantera"
echo "  ================="
echo ""
echo "  PRIMARIES"
swatch "#6B50FF" "Charple"  "primary (indigo)"
swatch "#FF60FF" "Dolly"    "secondary (magenta)"
swatch "#68FFD6" "Bok"      "accent (mint)"
swatch "#FF84FF" "Blush"    "keyword (pink)"
swatch "#FF985A" "Tang"     "attention (orange)"
swatch "#00A4FF" "Malibu"   "info (blue)"
swatch "#FF577D" "Coral"    "red / error"
swatch "#00FFB2" "Julep"    "success (green)"
swatch "#E8FF27" "Citron"   "busy (yellow)"
swatch "#E8FE96" "Zest"     "yolo (lime)"
echo ""
echo "  CHARPLE RAMP"
swatch "#4A30D9" "Jelly"    "darkest"
swatch "#5B40EC" "Darple"   "dark"
swatch "#6B50FF" "Charple"  "base"
swatch "#7B62FF" "Larple"   "light"
swatch "#8B75FF" "Hazy"     "lightest"
echo ""
echo "  NEUTRALS"
swatch "#201F26" "Pepper"   "darkest bg"
swatch "#2D2C36" "BBQ"      "dark bg"
swatch "#3A3943" "Char"     "border"
swatch "#4D4C57" "Iron"     "muted"
swatch "#605F6B" "Oyster"   "dim"
swatch "#858392" "Squid"    "subtle text"
swatch "#A2A0AD" "Steam"    "secondary text"
swatch "#BFBCC8" "Smoke"    "light text"
swatch "#D6D3DC" "Steep"    "bright text"
swatch "#ECEBF0" "Sash"     "foreground"
swatch "#F7F6FB" "Salt"     "near-white"
swatch "#FBFBFB" "Soda"     "white"
echo ""
echo "  ANSI REMAPPING"
swatch "#2D2C36" "BBQ"      "black"
swatch "#FF577D" "Coral"    "red"
swatch "#12C78F" "Guac"     "green"
swatch "#F5EF34" "Mustard"  "yellow"
swatch "#6B50FF" "Charple"  "blue"
swatch "#FF60FF" "Dolly"    "magenta"
swatch "#00A4FF" "Malibu"   "cyan"
swatch "#BFBCC8" "Smoke"    "white"
swatch "#4D4C57" "Iron"     "bright black"
swatch "#FF6DAA" "Tuna"     "bright red"
swatch "#00FFB2" "Julep"    "bright green"
swatch "#E8FE96" "Zest"     "bright yellow"
swatch "#7272FF" "Guppy"    "bright blue"
swatch "#FF84FF" "Blush"    "bright magenta"
swatch "#4FBEFE" "Sardine"  "bright cyan"
swatch "#F7F6FB" "Salt"     "bright white"
echo ""
